# Generated by Django 4.0.6 on 2023-07-30 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='thmbnail',
            new_name='thumbnail',
        ),
    ]
